/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 192dc07a19cd0c3ad3040845b2ec9da2)
interface __BaseEnv_Env {
	LOADER: WorkerLoader;
	PiAgent: DurableObjectNamespace<import("./src/server").PiAgent>;
	GUARDIAN: Service /* entrypoint GuardianRpc from core-guardian */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "PiAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
